### ISSUE TITLE
Update CONTEXT_URL_V3

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/open-badges-context#5]
The documentation references CONTEXT_URL_V3 which uses the OBv2 URL. The documentation doesn't mention CONTEXT_URL_V3_IMS or CONTEXT_URL_V3_JFF_V1.

Suggest

- CONTEXT_URL_V3_IMS and CONTEXT_URL_V3_JFF_V1 be removed
- CONTEXT_URL_V3 reference https://purl.imsglobal.org/spec/ob/v3p0/context.json or evaluate (https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.1.json)
- update index.js
- Check context.js for accuracy

**Comment by dmitrizagidulin** [comment]
Addressed in PR #7, published to NPM as `2.0.0`
